### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException

### ISSUE THREAD

**Issue by wankey** [FrangSierra/Rx2Firebase#20]
When I signIn with wrong password ,I got the exception below. What's wrong with it? I had call doOnError().

`RxFirebaseAuth.signInWithEmailAndPassword(mAuth, email, password).doOnSuccess(new Consumer<AuthResult>() {
            @Override
            public void accept(final AuthResult authResult) throws Exception {
                mView.signInSuccess(authResult.getUser().getDisplayName(), authResult.getUser().getPhotoUrl());
            }
        }).doOnError(new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) {
                mView.signInFailed(throwable.getMessage());
            }
        }).subscribe();`

> io.reactivex.exceptions.OnErrorNotImplementedException: The password is invalid or the user does not have a password.
                                                                                    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                                    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                                    at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:81)
                                                                                    at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
                                                                                    at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
                                                                                    at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
                                                                                    at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
                                                                                    at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
                                                                                    at durdinapps.rxfirebase2.RxHandler.onFailure(RxHandler.java:49)
                                                                                    at com.google.android.gms.tasks.zzd$1.run(Unknown Source)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                 Caused by: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The password is invalid or the user does not have a password.
                                                                                    at com.google.android.gms.internal.zzblv.zzce(Unknown Source)
                                                                                    at com.google.android.gms.internal.zzbls$zzj.zza(Unknown Source)
                                                                                    at com.google.android.gms.internal.zzbmd.zzcf(Unknown Source)
                                                                                    at com.google.android.gms.internal.zzbmd$zza.onFailure(Unknown Source)
                                                                                    at com.google.android.gms.internal.zzbly$zza.onTransact(Unknown Source)
                                                                                    at android.os.Binder.execTransact(Binder.java:453)

**Comment by FrangSierra** [comment]
`doOnError` is executed after, it just execute an action when an error is throwed. But you must implement a call to onError inside the subscriber:
`RxFirebaseAuth.signInWithEmailAndPassword(auth, email, password)
         .filter(authResult -> authResult.getUser() != null)
         .subscribe(authResult -> {
            //MANAGE YOUR ON SUCCESS HERE   
         }, throwable -> {
            //MANAGE YOUR ERROR HERE               
         })`
